import Head from "next/head";
import Image from "next/image";
import ConnectWallet from "../components/ConnectWallet";
import GameDetails from "../components/GameDetails";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import EthersContext from "../context/ethers-context";
import EnterGame from "../components/EnterGame";

export default function Home() {
  const ethersCtx = useContext(EthersContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectWallet />

      <main className={styles.main}>
        <h1 className={styles.title}>Eth Number Game 🎲</h1>
        {ethersCtx.contract && <GameDetails />}
        {ethersCtx.contract && <EnterGame />}
      </main>
    </div>
  );
}
